name: Snyk Code Scan for OWASP Juice Shop PR Changes

on:
  pull_request:
    branches:
      - master
    types:
      - opened      # Trigger on PR creation
      - synchronize # Trigger on PR updates
      - reopened    # Trigger if PR is reopened

jobs:
  snyk_code_scan:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to compare changes

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Snyk CLI
      - name: Install Snyk
        run: npm install -g snyk@latest

      # Check Snyk Version
      - name: Check Snyk Version
        run: snyk --version

      # Get changed files in the PR
      - name: Get Changed Files
        id: changed_files
        run: |
          git fetch origin master
          CHANGED_FILES=$(git diff --name-only origin/master...HEAD | tr '\n' ' ' || true)
          echo "Changed files: $CHANGED_FILES"  # Debug output
          echo "files=$CHANGED_FILES" >> "$GITHUB_OUTPUT"

      # Run Snyk code scan on changed JavaScript files only, with enhanced debugging
      - name: Snyk Code Scan
        id: snyk_code_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -z "${SNYK_TOKEN}" ]; then
            echo "Error: SNYK_TOKEN is not set"
            exit 1
          fi
          CHANGED_FILES="${{ steps.changed_files.outputs.files }}"
          echo "Scanning changed files: $CHANGED_FILES"
          if [ -n "$CHANGED_FILES" ]; then
            TOTAL_VULN=0
            for FILE in $CHANGED_FILES; do
              if [[ "$FILE" == *.js ]]; then
                echo "Scanning file: $FILE"
                if [ ! -f "$FILE" ]; then
                  echo "Error: File $FILE not found in repository"
                  continue
                fi
                # Scan without severity threshold to report all vulnerabilities, with detailed output
                snyk code test --file="$FILE" --json > "snyk-code-report-${FILE//\//_}.json" 2> "snyk-code-log-${FILE//\//_}.txt" || true
                # Debug: Show Snyk command output, log file, and verify file existence
                echo "Snyk command output for $FILE: $(cat snyk-code-log-${FILE//\//_}.txt || echo 'No output')"
                # Check if Snyk scanned only the specified file by inspecting the report
                if [ -s "snyk-code-report-${FILE//\//_}.json" ]; then
                  # Validate SARIF structure and debug
                  echo "Validating Snyk report for $FILE"
                  if jq -e '.runs[0].results' > /dev/null 2>&1 < "snyk-code-report-${FILE//\//_}.json"; then
                    if jq -e '.runs[0].results | map(.locations[].physicalLocation.artifactLocation.uri) | unique | . == ["'"$FILE"'"]' > /dev/null 2>&1 < "snyk-code-report-${FILE//\//_}.json"; then
                      echo "Confirmed scan limited to $FILE"
                      VULN_COUNT=$(jq '.runs[0].results | length // 0' "snyk-code-report-${FILE//\//_}.json" 2>/dev/null || echo 0)
                      echo "Vulnerabilities in $FILE: $VULN_COUNT"
                      echo "Snyk Code Report Content: $(cat snyk-code-report-${FILE//\//_}.json || echo 'Empty or invalid')"
                      TOTAL_VULN=$((TOTAL_VULN + VULN_COUNT))
                    else
                      echo "Warning: Snyk scanned files beyond $FILE. Limiting report to $FILE only."
                      jq 'del(.runs[].results[] | select(.locations[].physicalLocation.artifactLocation.uri != "'"$FILE"'"))' "snyk-code-report-${FILE//\//_}.json" > "filtered-snyk-code-report-${FILE//\//_}.json"
                      if [ -s "filtered-snyk-code-report-${FILE//\//_}.json" ]; then
                        VULN_COUNT=$(jq '.runs[0].results | length // 0' "filtered-snyk-code-report-${FILE//\//_}.json" 2>/dev/null || echo 0)
                        echo "Vulnerabilities in $FILE after filtering: $VULN_COUNT"
                        echo "Filtered Snyk Code Report Content: $(cat filtered-snyk-code-report-${FILE//\//_}.json || echo 'Empty or invalid')"
                        TOTAL_VULN=$((TOTAL_VULN + VULN_COUNT))
                        mv "filtered-snyk-code-report-${FILE//\//_}.json" "snyk-code-report-${FILE//\//_}.json"
                      else
                        echo "No vulnerabilities found in $FILE after filtering"
                      fi
                    fi
                  else
                    echo "Warning: Snyk report for $FILE has no results or invalid structure"
                  fi
                else
                  echo "No vulnerabilities found or scan failed for $FILE"
                fi
              fi
            done
            echo "code_vuln_count=$TOTAL_VULN" >> "$GITHUB_OUTPUT"
          else
            echo "code_vuln_count=0" >> "$GITHUB_OUTPUT"
          fi

      # Generate comment based on scan results for changed JavaScript files only, with fixed heredoc and desired format
      - name: Generate Scan Comment
        id: comment
        run: |
          {
            echo "body<<EOF"
            echo "## Snyk Code Scan Results for OWASP Juice Shop PR Changes"
            echo ""
            
            CHANGED_FILES="${{ steps.changed_files.outputs.files }}"
            if [ -n "$CHANGED_FILES" ]; then
              VULN_FOUND=false
              for FILE in $CHANGED_FILES; do
                if [[ "$FILE" == *.js ]]; then
                  REPORT_FILE="snyk-code-report-${FILE//\//_}.json"
                  if [ -s "$REPORT_FILE" ]; then
                    # Use jq with error handling to count vulnerabilities
                    VULN_COUNT=$(jq '.runs[0].results | length // 0' "$REPORT_FILE" 2>/dev/null || echo 0)
                    if [ "$VULN_COUNT" -gt 0 ]; then
                      VULN_FOUND=true
                      echo "### Vulnerabilities in \"$FILE\""
                      echo "Found $VULN_COUNT potential vulnerabilities in this file:"
                      # List vulnerabilities with text and line range for simplicity
                      for ((i=0; i<$VULN_COUNT; i++)); do
                        VULN_TEXT=$(jq -r '.runs[0].results['"$i"'].message.text // "No description available"' "$REPORT_FILE" 2>/dev/null || echo "No description available")
                        START_LINE=$(jq -r '.runs[0].results['"$i"'].locations[0].physicalLocation.region.startLine // "Unknown"' "$REPORT_FILE" 2>/dev/null || echo "Unknown")
                        END_LINE=$(jq -r '.runs[0].results['"$i"'].locations[0].physicalLocation.region.endLine // "Unknown"' "$REPORT_FILE" 2>/dev/null || echo "Unknown")
                        echo "- $VULN_TEXT (Lines $START_LINE–$END_LINE)"
                      done
                      echo "To view details, download the \"snyk-code-report-${FILE//\//_}.json\" artifact from GitHub Actions."
                      echo ""
                    fi
                  else
                    echo "Report file $REPORT_FILE is empty or invalid, skipping" >&2
                  fi
                fi
              done
              if [ "$VULN_FOUND" = false ]; then
                echo "### Code Vulnerabilities"
                echo "No vulnerabilities found in changed JavaScript code."
                echo ""
              fi
            else
              echo "### Code Vulnerabilities"
              echo "No changed files detected in this PR."
              echo ""
            fi
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      # Post comment to PR
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `${{ steps.comment.outputs.body }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });

      # Upload scan reports and logs as artifacts
      - name: Upload Snyk Code Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-report
          path: snyk-code-report-*.json

      - name: Upload Snyk Code Logs
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-logs
          path: snyk-code-log-*.txt

      # Upload filtered reports for debugging (optional)
      - name: Upload Filtered Snyk Code Reports (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: filtered-snyk-code-report
          path: filtered-snyk-code-report-*.json
