name: Snyk Code Scan for OWASP Juice Shop PR Changes

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  snyk_code_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk
        run: npm install -g snyk@latest

      - name: Get Changed Files
        id: changed_files
        run: |
          git fetch origin master
          CHANGED_FILES=$(git diff --name-only origin/master...HEAD | tr '\n' ' ' || true)
          echo "Changed files: $CHANGED_FILES"
          echo "files=$CHANGED_FILES" >> "$GITHUB_OUTPUT"

      - name: Snyk Code Scan
        id: snyk_code_scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          CHANGED_FILES="${{ steps.changed_files.outputs.files }}"
          echo "Scanning changed files: $CHANGED_FILES"
          if [ -n "$CHANGED_FILES" ]; then
            TOTAL_VULN=0
            for FILE in $CHANGED_FILES; do
              if [[ "$FILE" == *.js ]]; then
                echo "Scanning file: $FILE"
                snyk code test --file="$FILE" --json > "snyk-code-report-${FILE//\//_}.json" 2> "snyk-code-log-${FILE//\//_}.txt" || true

                if [ -s "snyk-code-report-${FILE//\//_}.json" ]; then
                  if jq -e '.runs[0].results | map(.locations[].physicalLocation.artifactLocation.uri) | unique | . == ["'"$FILE"'"]' > /dev/null 2>&1 < "snyk-code-report-${FILE//\//_}.json"; then
                    echo "Confirmed scan limited to $FILE"
                    VULN_COUNT=$(jq '.runs[0].results | length' "snyk-code-report-${FILE//\//_}.json")
                    TOTAL_VULN=$((TOTAL_VULN + VULN_COUNT))
                  else
                    jq 'del(.runs[].results[] | select(.locations[].physicalLocation.artifactLocation.uri != "'"$FILE"'"))' "snyk-code-report-${FILE//\//_}.json" > "filtered-snyk-code-report-${FILE//\//_}.json"
                    if [ -s "filtered-snyk-code-report-${FILE//\//_}.json" ]; then
                      VULN_COUNT=$(jq '.runs[0].results | length' "filtered-snyk-code-report-${FILE//\//_}.json")
                      TOTAL_VULN=$((TOTAL_VULN + VULN_COUNT))
                      mv "filtered-snyk-code-report-${FILE//\//_}.json" "snyk-code-report-${FILE//\//_}.json"
                    fi
                  fi
                fi
              fi
            done
            echo "code_vuln_count=$TOTAL_VULN" >> $GITHUB_OUTPUT
          else
            echo "code_vuln_count=0" >> $GITHUB_OUTPUT
          fi

      - name: Generate Scan Comment
        id: comment
        run: |
          COMMENT="## Snyk Code Scan Results for OWASP Juice Shop PR Changes\n\n"

          CHANGED_FILES="${{ steps.changed_files.outputs.files }}"
          if [ -n "$CHANGED_FILES" ]; then
            VULN_FOUND=false
            for FILE in $CHANGED_FILES; do
              if [[ "$FILE" == *.js ]]; then
                REPORT_FILE="snyk-code-report-${FILE//\//_}.json"
                if [ -s "$REPORT_FILE" ] && jq -e . > /dev/null 2>&1 < "$REPORT_FILE"; then
                  VULN_COUNT=$(jq '.runs[0].results | length' "$REPORT_FILE")
                  if [ "$VULN_COUNT" -gt 0 ]; then
                    VULN_FOUND=true
                    COMMENT="$COMMENT### Vulnerabilities in \`$FILE\`\n\n"
                    COMMENT="$COMMENTFound $VULN_COUNT potential vulnerabilities in this file.\n"
                    COMMENT="$COMMENTTo view details, download the \`snyk-code-report-${FILE//\//_}.json\` artifact from GitHub Actions.\n\n"

                    jq -c '.runs[0].results[]' "$REPORT_FILE" | while read -r vuln; do
                      RULE_ID=$(echo "$vuln" | jq -r '.ruleId')
                      DESCRIPTION=$(echo "$vuln" | jq -r '.message.text')

                      START_LINE=$(echo "$vuln" | jq -r '.locations[0].physicalLocation.region.startLine')
                      END_LINE=$(echo "$vuln" | jq -r '.locations[0].physicalLocation.region.endLine')
                      START_COLUMN=$(echo "$vuln" | jq -r '.locations[0].physicalLocation.region.startColumn')
                      END_COLUMN=$(echo "$vuln" | jq -r '.locations[0].physicalLocation.region.endColumn')

                      COMMENT="$COMMENT### ⚠️ Vulnerability\n"
                      COMMENT="$COMMENT- **Rule ID:** $RULE_ID\n"
                      COMMENT="$COMMENT- **Description:** $DESCRIPTION\n"
                      COMMENT="$COMMENT- **Location:**\n"
                      COMMENT="$COMMENT    - **Start Line:** $START_LINE\n"
                      COMMENT="$COMMENT    - **End Line:** $END_LINE\n"
                      COMMENT="$COMMENT    - **Start Column:** $START_COLUMN\n"
                      COMMENT="$COMMENT    - **End Column:** $END_COLUMN\n\n"
                    done
                  fi
                fi
              fi
            done

            if [ "$VULN_FOUND" = false ]; then
              COMMENT="$COMMENT### Code Vulnerabilities\nNo vulnerabilities found in changed JavaScript code.\n"
            fi
          else
            COMMENT="$COMMENT### Code Vulnerabilities\nNo changed files detected in this PR.\n"
          fi

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `${{ steps.comment.outputs.body }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });

      - name: Upload Snyk Code Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-report
          path: snyk-code-report-*.json

      - name: Upload Snyk Code Logs
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-logs
          path: snyk-code-log-*.txt

      - name: Upload Filtered Snyk Code Reports (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: filtered-snyk-code-report
          path: filtered-snyk-code-report-*.json
